name: ccl_python
channels:
- conda-forge
- defaults
dependencies:
- numpy
- pandas
- scikit-learn
- matplotlib
- seaborn
- holoviews
- notebook
- xlrd
- geopandas
- cartopy
- folium
- scikit-optimize

